language: java

# explicit distribution specification
# to use xvfb as a service
dist: xenial

jdk: openjdk8

git:
  depth: false

services:
   - docker
   - xvfb

addons:
  sonarcloud:
    organization: "josephthachilgeorge"
    token:
      secure: "AWS_SECRET_KEY" # encrypted value of your token

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
   - mvn -f simple-sonarqube-example/pom.xml -Pjacoco clean verify sonar:sonar
